// TODO: Source from Github
module.exports.availableModules = [
  'stripes-connect',
  'stripes-components',
  'stripes-smart-components',
  'stripes-react-hotkeys',
  'stripes-logger',
  'stripes-form',
  'stripes-core',
  'stripes-sample-platform',
  'folio-testing-platform',
  'ui-users',
  'ui-inventory',
  'ui-eholdings',
  'ui-checkin',
  'ui-checkout',
  'ui-circulation',
  'ui-organization',
  'ui-developer',
  'ui-plugin-example',
  'ui-plugin-find-user',
  'ui-requests',
  'ui-search',
  'ui-testing',
  'ui-trivial',
  'ui-items',
  'eslint-config-stripes',
];
